### ISSUE TITLE
Sending not valid captcha

### ISSUE THREAD

**Issue by BaHeK1994** [RubtsovAV/yandex-wordstat-parser#1]
![yandex-captcha1](https://user-images.githubusercontent.com/18642618/36475381-7c7b6654-170b-11e8-8ade-6d44d4b14e69.png)
![yandex-captcha2](https://user-images.githubusercontent.com/18642618/36475383-7c9651bc-170b-11e8-9e0c-4b31796ca044.png)

**Comment by BaHeK1994** [comment]
problem in ReactPhantomJs

**Comment by TechAlchemistry** [comment]
@BaHeK1994 Thank you. I will try to research this issue tomorrow. 
P.s. I recommend using Guzzle6, because PhantomJS has another strange problem (there need to rewrite the message system from STD to HTTP).

**Comment by BaHeK1994** [comment]
Фантом лучше эмитирует поведение браузера.
При использовании Guzzle6 вылетает в среднем 1-2 каптчи для 1 поиска (прогнал 7 слов, получил 11 картинок)
При фантоме 1 каптча на 15-20 поисков (прогнал 2 раза по 7 слов, только на 3-ий раз вылезла каптча)

**Comment by TechAlchemistry** [comment]
Это да. Но там надо допилить его. Но фантом и более прожорливый в ресурсах.

**Comment by TechAlchemistry** [comment]
Там иногда почему то Message битые через stdin stdout приходят. Я так и не додебажил.

**Comment by TechAlchemistry** [comment]
@BaHeK1994 I can't repeat this issue. Do you can?

**Comment by BaHeK1994** [comment]
![1519754875317](https://user-images.githubusercontent.com/18642618/36746199-bd43c52c-1c02-11e8-85aa-be64b1949e45.jpg)
![1519755046435](https://user-images.githubusercontent.com/18642618/36746200-bd62ecfe-1c02-11e8-93fe-8c15dffb8b7e.jpg)
Проблема актуальна

**Comment by TechAlchemistry** [comment]
Не воспроизводится.
