### ISSUE TITLE
После поиска слова не закрывается процесс phantomjs

### ISSUE THREAD

**Issue by BaHeK1994** [RubtsovAV/yandex-wordstat-parser#3]
![1520012704331](https://user-images.githubusercontent.com/18642618/36913363-c53c8ae8-1e5a-11e8-9ad8-29b671840176.jpg)
![1520012717971](https://user-images.githubusercontent.com/18642618/36913364-c55b794e-1e5a-11e8-9aa5-791e04e990e7.jpg)
С каждым словом кол-во процессов растет до бесконечности, отсюда высокая нагрузка.

**Comment by TechAlchemistry** [comment]
Я эту проблему фиксил. Ты мастер берешь?

**Comment by BaHeK1994** [comment]
Да, вот данные из composer.lock, последний коммит в данный момент
![1520062701362](https://user-images.githubusercontent.com/18642618/36931807-1280d8e4-1ecf-11e8-9f90-ed840e3ef4c9.jpg)

**Comment by TechAlchemistry** [comment]
В общем надо тестами обкладывать. 

Советую юзать пока guzzle - он стабильнее. Или еще можно выяснить каким запросом яндекс определяет, что это браузер и слать его Guzzl-ом.

**Comment by TechAlchemistry** [comment]
@BaHeK1994 Спасибо за репорт. Баг пофиксил. Теперь можно уверенно юзать PhantomJS - там гораздо реже попадается капча. Как правило вообще не попадается (зависит от прокси).
